from __future__ import annotations
from inline_snapshot import snapshot
from lib.japanese_deinflect.deinflect import Deinflector
from lib.japanese_deinflect.word_type import WordType
from lib.japanese_deinflect.derivations import rules


def assert_derivation_path_matches(word_to_deconjugate, expected_deconjugated_result, *derivation_path):
    deinflector = Deinflector()
    results = deinflector.unconjugate(word_to_deconjugate)
    assert len(results) > 0, f"No results for {word_to_deconjugate}"

    best_result = results[0]
    assert best_result["base"] == expected_deconjugated_result, f'Deconjugated word is not as expected for {word_to_deconjugate}. Expected: {expected_deconjugated_result} Actual: {best_result["base"]}'

    actual_derivation_path = [d for d in best_result["derivation_sequence"]["derivations"]]
    

    assert list(derivation_path) == actual_derivation_path, f'Test for word_to_deconjugate: {word_to_deconjugate} failed.\nDesired derivation path: {list(derivation_path)}\nActual derivation path: {actual_derivation_path}'


def test_grammar_rules():
    assert_derivation_path_matches('言ってもいいですよ', '言う', WordType.TE_FORM, WordType.MO_AFTER_TE, WordType.II, WordType.POLITE_DESU_VERB, WordType.YO_PARTICLE)
    assert_derivation_path_matches('遊べそうじゃないね', '遊ぶ', WordType.POTENTIAL, WordType.MASU_STEM, WordType.APPEARANCE, WordType.DA, WordType.NEGATIVE_NAI_VERB, WordType.NE_PARTICLE)
    # assert_derivation_path_matches('誘ってもらわれてくれなかった', '誘う', WordType.TE_FORM, WordType.MORAU, WordType.PASSIVE, WordType.TE_FORM, WordType.KURERU, WordType.NEGATIVE_NAI_VERB, WordType.PLAIN_PAST)
    assert_derivation_path_matches('遊んでるべく', '遊ぶ', WordType.TE_FORM, WordType.SHORT_IRU, WordType.BEKU)
    assert_derivation_path_matches('敷きやがりなさい', '敷く', WordType.MASU_STEM, WordType.YAGARU, WordType.MASU_STEM, WordType.NASAI)
    assert_derivation_path_matches('重なり次第だ', '重なる', WordType.MASU_STEM, WordType.SHIDAI, WordType.DA)
    assert_derivation_path_matches('生き過ぎだ', '生きる', WordType.MASU_STEM, WordType.SUGI, WordType.DA)
    assert_derivation_path_matches('覚え難いの', '覚える', WordType.MASU_STEM, WordType.GATAI, WordType.EXPLANATORY_NO_PARTICLE)
    assert_derivation_path_matches('覚えがたいよ', '覚える', WordType.MASU_STEM, WordType.GATAI, WordType.YO_PARTICLE)
    assert_derivation_path_matches('飛びつつあった', '飛ぶ', WordType.MASU_STEM, WordType.TSUTSU_ARU, WordType.PLAIN_PAST)
    assert_derivation_path_matches('笑いたいのでありたい', '笑う', WordType.MASU_STEM, WordType.TAI, WordType.EXPLANATORY_NO_PARTICLE, WordType.DA, WordType.DE_ARU, WordType.MASU_STEM, WordType.TAI)
    assert_derivation_path_matches('笑いたくなった', '笑う', WordType.MASU_STEM, WordType.TAI, WordType.ADVERB, WordType.NARU, WordType.PLAIN_PAST)
    assert_derivation_path_matches('笑うはずです', '笑う', WordType.HAZU, WordType.DA, WordType.POLITE_DESU_VERB)
    assert_derivation_path_matches('笑わないようだろう', '笑う', WordType.NEGATIVE_NAI_VERB, WordType.YOU, WordType.DA, WordType.DAROU)
    assert_derivation_path_matches('笑ったようね', '笑う', WordType.PLAIN_PAST, WordType.YOU, WordType.NE_PARTICLE)
    assert_derivation_path_matches('来たばかりです', '来る', WordType.PLAIN_PAST, WordType.TA_BAKARI, WordType.DA, WordType.POLITE_DESU_VERB)
    assert_derivation_path_matches('死んじゃったりして', '死ぬ', WordType.TE_FORM, WordType.SHIMAU, WordType.JAU, WordType.TARI, WordType.TE_FORM)
    assert_derivation_path_matches('死んじゃったら', '死ぬ', WordType.TE_FORM, WordType.SHIMAU, WordType.JAU, WordType.TARA)
    assert_derivation_path_matches('叫んですみませんでした', '叫ぶ', WordType.TE_FORM, WordType.SUMANAI, WordType.SUMIMASEN, WordType.POLITE_MASEN_DESHITA)
    assert_derivation_path_matches('沈んでもかまわない', '沈む', WordType.TE_FORM, WordType.MO_AFTER_TE, WordType.KAMAU, WordType.NEGATIVE_NAI_VERB)
    assert_derivation_path_matches('沈んでいった', '沈む', WordType.TE_FORM, WordType.TE_IKU, WordType.PLAIN_PAST)
    assert_derivation_path_matches('上がってくよ', '上がる', WordType.TE_FORM, WordType.TE_IKU, WordType.YO_PARTICLE)
    assert_derivation_path_matches('話してこないだろう', '話す', WordType.TE_FORM, WordType.TE_KURU, WordType.NEGATIVE_NAI_VERB, WordType.DAROU)
    assert_derivation_path_matches('終わらせてからでしょうね', '終わる', WordType.CAUSATIVE, WordType.TE_FORM, WordType.TE_KARA, WordType.DA, WordType.DAROU, WordType.POLITE_DESHOU, WordType.NE_PARTICLE)
    assert_derivation_path_matches('名乗って欲しかったな', '名乗る', WordType.TE_FORM, WordType.HOSHII, WordType.PLAIN_PAST, WordType.NA_PARTICLE)
    assert_derivation_path_matches('試してみてね', '試す', WordType.TE_FORM, WordType.MIRU, WordType.TE_FORM, WordType.NE_PARTICLE)
    assert_derivation_path_matches('忘れちゃったね', '忘れる', WordType.TE_FORM, WordType.SHIMAU, WordType.CHAU, WordType.PLAIN_PAST, WordType.NE_PARTICLE)
    assert_derivation_path_matches('見てあげなさい', '見る', WordType.TE_FORM, WordType.AGERU, WordType.MASU_STEM, WordType.NASAI)
    assert_derivation_path_matches('下がってくれよ', '下がる', WordType.TE_FORM, WordType.KURERU, WordType.IMPERATIVE, WordType.YO_PARTICLE)
    assert_derivation_path_matches('笑わなくてはいけないよ', '笑う', WordType.NEGATIVE_NAI_VERB, WordType.NAKUTE_NAKEREBA_IKENAI_NARANAI, WordType.YO_PARTICLE)
    assert_derivation_path_matches('笑っては駄目なのよ', '笑う', WordType.TE_FORM, WordType.TE_DAME, WordType.DA, WordType.EXPLANATORY_NO_PARTICLE, WordType.YO_PARTICLE)
    assert_derivation_path_matches('笑ってはいけないんだ', '笑う', WordType.TE_FORM, WordType.TE_IKENAI_NARANAI, WordType.EXPLANATORY_NO_PARTICLE, WordType.DA)
    assert_derivation_path_matches('笑ってはいけないのだ', '笑う', WordType.TE_FORM, WordType.TE_IKENAI_NARANAI, WordType.EXPLANATORY_NO_PARTICLE, WordType.DA)
    assert_derivation_path_matches('笑わなくてはいけないよ', '笑う', WordType.NEGATIVE_NAI_VERB, WordType.NAKUTE_NAKEREBA_IKENAI_NARANAI, WordType.YO_PARTICLE)
    assert_derivation_path_matches('笑わされる', '笑う', WordType.CAUSATIVE, WordType.SHORTENED_CAUSATIVE, WordType.PASSIVE)
    assert_derivation_path_matches('逃げてもいい', '逃げる', WordType.TE_FORM, WordType.MO_AFTER_TE, WordType.II)
    assert_derivation_path_matches('食べなくてよいよ', '食べる', WordType.NEGATIVE_NAI_VERB, WordType.TE_FORM, WordType.II, WordType.II, WordType.YO_PARTICLE)
    assert_derivation_path_matches('食べなくていいよ', '食べる', WordType.NEGATIVE_NAI_VERB, WordType.TE_FORM, WordType.II, WordType.YO_PARTICLE)
    assert_derivation_path_matches('食べなくてはいいよ', '食べる', WordType.NEGATIVE_NAI_VERB, WordType.TE_FORM, WordType.WA_AFTER_TE, WordType.II, WordType.YO_PARTICLE)
    assert_derivation_path_matches('食べに', '食べる', WordType.MASU_STEM, WordType.MASU_STEM_NI)
    assert_derivation_path_matches('逃げなよ', '逃げる', WordType.MASU_STEM, WordType.NASAI, WordType.YO_PARTICLE)
    assert_derivation_path_matches('逃げるなよ', '逃げる', WordType.NA_COMMAND, WordType.YO_PARTICLE)
    assert_derivation_path_matches('逃げやすいですね', '逃げる', WordType.MASU_STEM, WordType.YASUI, WordType.POLITE_DESU_VERB, WordType.NE_PARTICLE)
    assert_derivation_path_matches('逃げにくいですね', '逃げる', WordType.MASU_STEM, WordType.NIKUI, WordType.POLITE_DESU_VERB, WordType.NE_PARTICLE)
    assert_derivation_path_matches('逃げられすぎた', '逃げる', WordType.POTENTIAL_PASSIVE, WordType.MASU_STEM, WordType.SUGIRU, WordType.PLAIN_PAST)
    assert_derivation_path_matches('逃げられ過ぎた', '逃げる', WordType.POTENTIAL_PASSIVE, WordType.MASU_STEM, WordType.SUGIRU, WordType.PLAIN_PAST)
    assert_derivation_path_matches('逃げ方ですね', '逃げる', WordType.MASU_STEM, WordType.KATA, WordType.DA, WordType.POLITE_DESU_VERB, WordType.NE_PARTICLE)
    assert_derivation_path_matches('逃げかたですね', '逃げる', WordType.MASU_STEM, WordType.KATA, WordType.DA, WordType.POLITE_DESU_VERB, WordType.NE_PARTICLE)
    assert_derivation_path_matches('逃げがちですね', '逃げる', WordType.MASU_STEM, WordType.GACHI, WordType.DA, WordType.POLITE_DESU_VERB, WordType.NE_PARTICLE)
    assert_derivation_path_matches('追われながら', '追う', WordType.PASSIVE, WordType.MASU_STEM, WordType.NAGARA)
    assert_derivation_path_matches('出しはしないよ', '出す', WordType.MASU_STEM, WordType.MASU_STEM_WA_SHINAI, WordType.YO_PARTICLE)
    # assert_derivation_path_matches('行きたがっていますね', '行く', WordType.MASU_STEM, WordType.TAI, WordType.GARU, WordType.TE_FORM, WordType.IRU, WordType.MASU_STEM, WordType.POLITE_MASU, WordType.NE_PARTICLE)
    assert_derivation_path_matches('行くらしくないですね', '行く', WordType.RASHII, WordType.NEGATIVE_NAI_VERB, WordType.POLITE_DESU_VERB, WordType.NE_PARTICLE)
    assert_derivation_path_matches('信じられないみたいだね', '信じる', WordType.POTENTIAL_PASSIVE, WordType.NEGATIVE_NAI_VERB, WordType.MITAI, WordType.DA, WordType.NE_PARTICLE)
    assert_derivation_path_matches('信じられるが早いか', '信じる', WordType.POTENTIAL_PASSIVE, WordType.GA_HAYAI_KA)
    assert_derivation_path_matches('信じられるがはやいか', '信じる', WordType.POTENTIAL_PASSIVE, WordType.GA_HAYAI_KA, WordType.GA_HAYAI_KA)
    assert_derivation_path_matches('言われるまえだよ', '言う', WordType.PASSIVE, WordType.MAE, WordType.DA, WordType.YO_PARTICLE)
    assert_derivation_path_matches('言われる前だよ', '言う', WordType.PASSIVE, WordType.MAE, WordType.DA, WordType.YO_PARTICLE)
    assert_derivation_path_matches('言わないよ', '言う', WordType.NEGATIVE_NAI_VERB, WordType.YO_PARTICLE)
    assert_derivation_path_matches('おいておいたことになったのだ', 'おく', WordType.TE_FORM, WordType.OKU, WordType.PLAIN_PAST, WordType.KOTO_NI_NARU, WordType.PLAIN_PAST, WordType.EXPLANATORY_NO_PARTICLE, WordType.DA)
    assert_derivation_path_matches('おいておくことにした', 'おく', WordType.TE_FORM, WordType.OKU, WordType.KOTO_NI_SURU, WordType.PLAIN_PAST)
    assert_derivation_path_matches('返したことなのですよ', '返す', WordType.PLAIN_PAST, WordType.KOTO_NOMINALIZER, WordType.DA, WordType.EXPLANATORY_NO_PARTICLE, WordType.DA, WordType.POLITE_DESU_VERB, WordType.YO_PARTICLE)
    assert_derivation_path_matches('帰ったのだよ', '帰る', WordType.PLAIN_PAST, WordType.EXPLANATORY_NO_PARTICLE, WordType.DA, WordType.YO_PARTICLE)
    assert_derivation_path_matches('はしゃぐことがあることがあるだろうよ', 'はしゃぐ', WordType.OCCASIONAL_OCCURANCE_ARU, WordType.OCCASIONAL_OCCURANCE_ARU, WordType.DAROU, WordType.YO_PARTICLE)
    assert_derivation_path_matches('止めることができる', '止める', WordType.POTENTIAL)
    assert_derivation_path_matches('止めることができているよ', '止める', WordType.POTENTIAL, WordType.TE_FORM, WordType.IRU, WordType.YO_PARTICLE)
    assert_derivation_path_matches('止められるまでだよね', '止める', WordType.POTENTIAL_PASSIVE, WordType.MADE_PARTICLE, WordType.DA, WordType.YO_PARTICLE, WordType.NE_PARTICLE)
    assert_derivation_path_matches('停止せよ', '停止する', WordType.IMPERATIVE)
    assert_derivation_path_matches('書ければ', '書く', WordType.POTENTIAL, WordType.BA_FORM)
    assert_derivation_path_matches('離さなくない', '離す', WordType.NEGATIVE_NAI_VERB, WordType.NEGATIVE_NAI_VERB)
    assert_derivation_path_matches('離さなくなさそうです', '離す', WordType.NEGATIVE_NAI_VERB, WordType.NEGATIVE_NAI_VERB, WordType.APPEARANCE, WordType.DA, WordType.POLITE_DESU_VERB)
    assert_derivation_path_matches('離さなかろう', '離す', WordType.NEGATIVE_NAI_VERB, WordType.VOLITIONAL)
    assert_derivation_path_matches('離さないべき', '離す', WordType.NEGATIVE_NAI_VERB, WordType.BEKI)
    assert_derivation_path_matches('離さなかったらよければ', '離す', WordType.NEGATIVE_NAI_VERB, WordType.TARA, WordType.II, WordType.II, WordType.BA_FORM)
    assert_derivation_path_matches('来る', '来る')
    assert_derivation_path_matches('来ない', '来る', WordType.NEGATIVE_NAI_VERB)
    assert_derivation_path_matches('来た', '来る', WordType.PLAIN_PAST)
    assert_derivation_path_matches('来い', '来る', WordType.IMPERATIVE)
    assert_derivation_path_matches('せず', 'する', WordType.ZU)
    assert_derivation_path_matches('しない', 'する', WordType.NEGATIVE_NAI_VERB)
    assert_derivation_path_matches('しなければ', 'する', WordType.NEGATIVE_NAI_VERB, WordType.BA_FORM)
    assert_derivation_path_matches('言っとけた', '言う', WordType.TE_FORM, WordType.OKU, WordType.POTENTIAL, WordType.PLAIN_PAST)
    assert_derivation_path_matches('言って置かれた', '言う', WordType.TE_FORM, WordType.OKU, WordType.OKU, WordType.PASSIVE, WordType.PLAIN_PAST)
    assert_derivation_path_matches('確認すべきです', '確認する', WordType.BEKI, WordType.DA, WordType.POLITE_DESU_VERB)
    assert_derivation_path_matches('書けなさそうです', '書く', WordType.POTENTIAL, WordType.NEGATIVE_NAI_VERB, WordType.APPEARANCE, WordType.DA, WordType.POLITE_DESU_VERB)
    # assert_derivation_path_matches('離れていただけないでしょうか', '離れる', WordType.TE_FORM, WordType.MORAU, WordType.POLITE_ITADAKU, WordType.POTENTIAL, WordType.NEGATIVE_NAI_VERB, WordType.DAROU, WordType.POLITE_DESHOU, WordType.KA_PARTICLE)
    # assert_derivation_path_matches('離れてもらえないでしょうか', '離れる', WordType.TE_FORM, WordType.MORAU, WordType.POTENTIAL, WordType.NEGATIVE_NAI_VERB, WordType.DAROU, WordType.POLITE_DESHOU, WordType.KA_PARTICLE)
    assert_derivation_path_matches('離れてもらいたいです', '離れる', WordType.TE_FORM, WordType.MORAU, WordType.MASU_STEM, WordType.TAI, WordType.POLITE_DESU_VERB)
    assert_derivation_path_matches('励ます', '励ます')
    assert_derivation_path_matches('話します', '話す', WordType.MASU_STEM, WordType.POLITE_MASU)
    assert_derivation_path_matches('話すです', '話す', WordType.POLITE_DESU_VERB)
    assert_derivation_path_matches('信じます', '信じる', WordType.MASU_STEM, WordType.POLITE_MASU)
    assert_derivation_path_matches('信じるです', '信じる', WordType.POLITE_DESU_VERB)
    assert_derivation_path_matches('行きません', '行く', WordType.MASU_STEM, WordType.POLITE_MASEN)
    assert_derivation_path_matches('得ません', '得る', WordType.MASU_STEM, WordType.POLITE_MASEN)
    assert_derivation_path_matches('語らないです', '語る', WordType.NEGATIVE_NAI_VERB, WordType.POLITE_DESU_VERB)
    assert_derivation_path_matches('弾けない', '弾く', WordType.POTENTIAL, WordType.NEGATIVE_NAI_VERB)
    assert_derivation_path_matches('集まりました', '集まる', WordType.MASU_STEM, WordType.POLITE_MASU, WordType.POLITE_MASHITA)
    assert_derivation_path_matches('信じました', '信じる', WordType.MASU_STEM, WordType.POLITE_MASU, WordType.POLITE_MASHITA)
    assert_derivation_path_matches('笑いませんでした', '笑う', WordType.MASU_STEM, WordType.POLITE_MASEN, WordType.POLITE_MASEN_DESHITA)
    assert_derivation_path_matches('放った', '放る', WordType.PLAIN_PAST)
    assert_derivation_path_matches('覚えた', '覚える', WordType.PLAIN_PAST)
    assert_derivation_path_matches('言わなかった', '言う', WordType.NEGATIVE_NAI_VERB, WordType.PLAIN_PAST)
    assert_derivation_path_matches('照らなかった', '照る', WordType.NEGATIVE_NAI_VERB, WordType.PLAIN_PAST)
    assert_derivation_path_matches('咲いて', '咲く', WordType.TE_FORM)
    assert_derivation_path_matches('消えて', '消える', WordType.TE_FORM)
    assert_derivation_path_matches('解きまして', '解く', WordType.MASU_STEM, WordType.POLITE_MASU, WordType.TE_FORM)
    assert_derivation_path_matches('変わらなくて', '変わる', WordType.NEGATIVE_NAI_VERB, WordType.TE_FORM)
    assert_derivation_path_matches('打てば', '打つ', WordType.BA_FORM)
    assert_derivation_path_matches('打たなければ', '打つ', WordType.NEGATIVE_NAI_VERB, WordType.BA_FORM)
    assert_derivation_path_matches('置かれる', '置く', WordType.PASSIVE)
    assert_derivation_path_matches('置かれることがあるよ', '置く', WordType.PASSIVE, WordType.OCCASIONAL_OCCURANCE_ARU, WordType.YO_PARTICLE)
    assert_derivation_path_matches('得られる', '得る', WordType.POTENTIAL_PASSIVE)
    assert_derivation_path_matches('帰れる', '帰る', WordType.POTENTIAL)
    assert_derivation_path_matches('帰れなくて', '帰る', WordType.POTENTIAL, WordType.NEGATIVE_NAI_VERB, WordType.TE_FORM)
    assert_derivation_path_matches('帰れなければ', '帰る', WordType.POTENTIAL, WordType.NEGATIVE_NAI_VERB, WordType.BA_FORM)
    assert_derivation_path_matches('帰れました', '帰る', WordType.POTENTIAL, WordType.MASU_STEM, WordType.POLITE_MASU, WordType.POLITE_MASHITA)
    assert_derivation_path_matches('放たれました', '放つ', WordType.PASSIVE, WordType.MASU_STEM, WordType.POLITE_MASU, WordType.POLITE_MASHITA)
    assert_derivation_path_matches('黙れ', '黙る', WordType.IMPERATIVE)
    assert_derivation_path_matches('食べよう', '食べる', WordType.VOLITIONAL)
    assert_derivation_path_matches('殺されましょう', '殺す', WordType.PASSIVE, WordType.MASU_STEM, WordType.POLITE_MASU, WordType.POLITE_MASHOU)
    assert_derivation_path_matches('降りそう', '降りる', WordType.MASU_STEM, WordType.APPEARANCE)
    assert_derivation_path_matches('走れそう', '走る', WordType.POTENTIAL, WordType.MASU_STEM, WordType.APPEARANCE)
    assert_derivation_path_matches('殴られそう', '殴る', WordType.POTENTIAL_PASSIVE, WordType.MASU_STEM, WordType.APPEARANCE)
    assert_derivation_path_matches('買えそう', '買う', WordType.POTENTIAL, WordType.MASU_STEM, WordType.APPEARANCE)
    assert_derivation_path_matches('書かれそう', '書く', WordType.PASSIVE, WordType.MASU_STEM, WordType.APPEARANCE)
    assert_derivation_path_matches('走るそう', '走る', WordType.HEARSAY)
    assert_derivation_path_matches('得られるそう', '得る', WordType.POTENTIAL_PASSIVE, WordType.HEARSAY)
    assert_derivation_path_matches('押されるそう', '押す', WordType.PASSIVE, WordType.HEARSAY)
    assert_derivation_path_matches('食べれるそう', '食べる', WordType.POTENTIAL, WordType.HEARSAY)
    assert_derivation_path_matches('行かないそう', '行く', WordType.NEGATIVE_NAI_VERB, WordType.HEARSAY)
    assert_derivation_path_matches('行かなかったそう', '行く', WordType.NEGATIVE_NAI_VERB, WordType.PLAIN_PAST, WordType.HEARSAY)
    assert_derivation_path_matches('歌わせる', '歌う', WordType.CAUSATIVE)
    assert_derivation_path_matches('歌わせた', '歌う', WordType.CAUSATIVE, WordType.PLAIN_PAST)
    assert_derivation_path_matches('歌わす', '歌う', WordType.CAUSATIVE, WordType.SHORTENED_CAUSATIVE)
    assert_derivation_path_matches('歌わせられた', '歌う', WordType.CAUSATIVE, WordType.POTENTIAL_PASSIVE, WordType.PLAIN_PAST)
    assert_derivation_path_matches('歌わせない', '歌う', WordType.CAUSATIVE, WordType.NEGATIVE_NAI_VERB)
    assert_derivation_path_matches('歌わせたら', '歌う', WordType.CAUSATIVE, WordType.TARA)
    assert_derivation_path_matches('歌わせられたら', '歌う', WordType.CAUSATIVE, WordType.POTENTIAL_PASSIVE, WordType.TARA)
    assert_derivation_path_matches('歌わせなかったら', '歌う', WordType.CAUSATIVE, WordType.NEGATIVE_NAI_VERB, WordType.TARA)
    assert_derivation_path_matches('放たれましたら', '放つ', WordType.PASSIVE, WordType.MASU_STEM, WordType.POLITE_MASU, WordType.TARA)
    assert_derivation_path_matches('帰れたら', '帰る', WordType.POTENTIAL, WordType.TARA)
    assert_derivation_path_matches('置かれたら', '置く', WordType.PASSIVE, WordType.TARA)
    assert_derivation_path_matches('歌わせられなきゃ', '歌う', WordType.CAUSATIVE, WordType.POTENTIAL_PASSIVE, WordType.NEGATIVE_NAI_VERB, WordType.NAKYA)
    assert_derivation_path_matches('歌わせなきゃ', '歌う', WordType.CAUSATIVE, WordType.NEGATIVE_NAI_VERB, WordType.NAKYA)
    assert_derivation_path_matches('放たれなきゃ', '放つ', WordType.PASSIVE, WordType.NEGATIVE_NAI_VERB, WordType.NAKYA)
    assert_derivation_path_matches('放たれなくちゃ', '放つ', WordType.PASSIVE, WordType.NEGATIVE_NAI_VERB, WordType.NAKUCHA)
    assert_derivation_path_matches('歌わせられた挙句', '歌う', WordType.CAUSATIVE, WordType.POTENTIAL_PASSIVE, WordType.PLAIN_PAST, WordType.AGEKU)
    assert_derivation_path_matches('歌いたい', '歌う', WordType.MASU_STEM, WordType.TAI)
    assert_derivation_path_matches('歌いたくない', '歌う', WordType.MASU_STEM, WordType.TAI, WordType.NEGATIVE_NAI_VERB)
    assert_derivation_path_matches('歌いたくはない', '歌う', WordType.MASU_STEM, WordType.TAI, WordType.NEGATIVE_NAI_VERB)
    assert_derivation_path_matches('歌わせられたい', '歌う', WordType.CAUSATIVE, WordType.POTENTIAL_PASSIVE, WordType.MASU_STEM, WordType.TAI)
    assert_derivation_path_matches('歌わせたい', '歌う', WordType.CAUSATIVE, WordType.MASU_STEM, WordType.TAI)
    assert_derivation_path_matches('歌わせないで', '歌う', WordType.CAUSATIVE, WordType.NEGATIVE_NAI_VERB, WordType.NAIDE)
    assert_derivation_path_matches('食べさせられたかった', '食べる', WordType.CAUSATIVE, WordType.POTENTIAL_PASSIVE, WordType.MASU_STEM, WordType.TAI, WordType.PLAIN_PAST)
    assert_derivation_path_matches('行くな', '行く', WordType.NA_COMMAND)
    assert_derivation_path_matches('信じるな', '信じる', WordType.NA_COMMAND)
    assert_derivation_path_matches('行くまい', '行く', WordType.NEGATIVE_VOLITIONAL)
    assert_derivation_path_matches('信じるまい', '信じる', WordType.NEGATIVE_VOLITIONAL)
    assert_derivation_path_matches('話している', '話す', WordType.TE_FORM, WordType.IRU)
    assert_derivation_path_matches('話してある', '話す', WordType.TE_FORM, WordType.ARU)
    assert_derivation_path_matches('話しておる', '話す', WordType.TE_FORM, WordType.ORU)
    assert_derivation_path_matches('話していさせて', '話す', WordType.TE_FORM, WordType.IRU, WordType.CAUSATIVE, WordType.TE_FORM)
    assert_derivation_path_matches('離されて', '離す', WordType.PASSIVE, WordType.TE_FORM)
    assert_derivation_path_matches('離せて', '離す', WordType.POTENTIAL, WordType.TE_FORM)
    assert_derivation_path_matches('得られて', '得る', WordType.POTENTIAL_PASSIVE, WordType.TE_FORM)
    assert_derivation_path_matches('撫でさせられていさせて', '撫でる', WordType.CAUSATIVE, WordType.POTENTIAL_PASSIVE, WordType.TE_FORM, WordType.IRU, WordType.CAUSATIVE, WordType.TE_FORM)
    assert_derivation_path_matches('書かれてあった', '書く', WordType.PASSIVE, WordType.TE_FORM, WordType.ARU, WordType.PLAIN_PAST)
    # assert_derivation_path_matches('撫でさせられていさせなさい', '撫でる', WordType.CAUSATIVE, WordType.POTENTIAL_PASSIVE, WordType.TE_FORM, WordType.IRU, WordType.CAUSATIVE, WordType.MASU_STEM, WordType.NASAI)
    # assert_derivation_path_matches('撫でさせられていさせな', '撫でる', WordType.CAUSATIVE, WordType.POTENTIAL_PASSIVE, WordType.TE_FORM, WordType.IRU, WordType.CAUSATIVE, WordType.MASU_STEM, WordType.NASAI)
    # assert_derivation_path_matches('撫でさせられてはいさせな', '撫でる', WordType.CAUSATIVE, WordType.POTENTIAL_PASSIVE, WordType.TE_FORM, WordType.WA_AFTER_TE, WordType.IRU, WordType.CAUSATIVE, WordType.MASU_STEM, WordType.NASAI)
    assert_derivation_path_matches('書かず', '書く', WordType.ZU)
    assert_derivation_path_matches('書けず', '書く', WordType.POTENTIAL, WordType.ZU)
    assert_derivation_path_matches('書かれず', '書く', WordType.PASSIVE, WordType.ZU)
    assert_derivation_path_matches('撫でさせられていさせず', '撫でる', WordType.CAUSATIVE, WordType.POTENTIAL_PASSIVE, WordType.TE_FORM, WordType.IRU, WordType.CAUSATIVE, WordType.ZU)
    assert_derivation_path_matches('撫でさせられず', '撫でる', WordType.CAUSATIVE, WordType.POTENTIAL_PASSIVE, WordType.ZU)
    assert_derivation_path_matches('撫でさせられたく', '撫でる', WordType.CAUSATIVE, WordType.POTENTIAL_PASSIVE, WordType.MASU_STEM, WordType.TAI, WordType.ADVERB)
    assert_derivation_path_matches('撫でさせられたくなく', '撫でる', WordType.CAUSATIVE, WordType.POTENTIAL_PASSIVE, WordType.MASU_STEM, WordType.TAI, WordType.NEGATIVE_NAI_VERB, WordType.ADVERB)
    assert_derivation_path_matches('撫でさせられたくはなく', '撫でる', WordType.CAUSATIVE, WordType.POTENTIAL_PASSIVE, WordType.MASU_STEM, WordType.TAI, WordType.NEGATIVE_NAI_VERB, WordType.ADVERB)
    assert_derivation_path_matches('座ってはいる', '座る', WordType.TE_FORM, WordType.WA_AFTER_TE, WordType.IRU)
    assert_derivation_path_matches('されたくない', 'する', WordType.PASSIVE, WordType.MASU_STEM, WordType.TAI, WordType.NEGATIVE_NAI_VERB)
    assert_derivation_path_matches('書きません', '書く', WordType.MASU_STEM, WordType.POLITE_MASEN)
    assert_derivation_path_matches('しませんでした', 'する', WordType.MASU_STEM, WordType.POLITE_MASEN, WordType.POLITE_MASEN_DESHITA)
    assert_derivation_path_matches('為さいませんでした', '為さる', WordType.MASU_STEM, WordType.POLITE_MASEN, WordType.POLITE_MASEN_DESHITA)
    assert_derivation_path_matches('書いてください', '書く', WordType.TE_FORM, WordType.KUDASAI)
    assert_derivation_path_matches('撫でさせられぬ', '撫でる', WordType.CAUSATIVE, WordType.POTENTIAL_PASSIVE, WordType.NEGATIVE_NAI_VERB, WordType.NU)
    assert_derivation_path_matches('撫でさせられぬよ', '撫でる', WordType.CAUSATIVE, WordType.POTENTIAL_PASSIVE, WordType.NEGATIVE_NAI_VERB, WordType.NU, WordType.YO_PARTICLE)
    assert_derivation_path_matches('撫でさせられぬよね', '撫でる', WordType.CAUSATIVE, WordType.POTENTIAL_PASSIVE, WordType.NEGATIVE_NAI_VERB, WordType.NU, WordType.YO_PARTICLE, WordType.NE_PARTICLE)
    assert_derivation_path_matches('仰いませんでした', '仰る', WordType.MASU_STEM, WordType.POLITE_MASEN, WordType.POLITE_MASEN_DESHITA)
    assert_derivation_path_matches('話してあるだろう', '話す', WordType.TE_FORM, WordType.ARU, WordType.DAROU)
    assert_derivation_path_matches('話してあるでしょう', '話す', WordType.TE_FORM, WordType.ARU, WordType.DAROU, WordType.POLITE_DESHOU)
    assert_derivation_path_matches('行った方が良くないよ', '行う', WordType.PLAIN_PAST, WordType.HOU_GA_II, WordType.NEGATIVE_NAI_VERB, WordType.YO_PARTICLE)


def test_fuzzy_derivation():
    deinflector = Deinflector()
    results = deinflector.unconjugate('仰いませんでしたじゃやらぱが', fuzzy=True)
    assert len(results) > 0


def test_word_type_validation():
    """Test that all derivation rules have valid word types"""
    for rule in rules:
        assert rule.get('unconjugated_word_type') is not None, f'No unconjugated word type for {rule.get("unconjugated_ending")} -> {rule.get("conjugated_ending")}'
        assert rule.get('conjugated_word_type') is not None, f'No conjugated word type for {rule.get("unconjugated_ending")} -> {rule.get("conjugated_ending")}'
        assert rule.get('conjugated_ending') is not None, f'No conjugated ending for {rule.get("unconjugated_ending")} -> {rule.get("conjugated_ending")}'
        assert rule.get('unconjugated_ending') is not None, f'No unconjugated ending for {rule.get("unconjugated_ending")} -> {rule.get("conjugated_ending")}'


def test_maximum_recursion_depth():
    """Test that maximum recursion depth is respected"""
    deinflector = Deinflector()
    # Test with a complex conjugated form that would normally require deep recursion
    results_with_limit = deinflector.unconjugate('撫でさせられぬよね', recursion_depth_limit=3)
    results_without_limit = deinflector.unconjugate('撫でさせられぬよね', recursion_depth_limit=10)
    
    # With a low recursion limit, we should get fewer or no results
    # With a higher limit, we should get more results
    assert len(results_with_limit) <= len(results_without_limit)
