// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentConstituent } from "./DocumentConstituent";
import type { Phrase } from "./Phrase";

export interface AnnotatedDocument {
  type: "AnnotatedDocument";
  text: string;
  constituents: Array<DocumentConstituent>;
  num_sentences: number;
  num_tokens: number;
  token_texts: Array<string>;
  phrases: Array<Phrase> | null;
}
