// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SentenceConstituent } from "./SentenceConstituent";

export type DocumentConstituent = {
  "type": "Sentence";
  id: number;
  text: string;
  start_char: number;
  end_char: number;
  constituents: Array<SentenceConstituent>;
} | {
  "type": "Whitespace";
  text: string;
  start_char: number;
  end_char: number;
};
