// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentConstituent } from "./DocumentConstituent";

export interface Document {
  type: "Document";
  text: string;
  constituents: Array<DocumentConstituent>;
  num_sentences: number;
  num_tokens: number;
}
