// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LanguageEntry {
  id: { tb: string; id: { String: string } };
  code: string;
  name: string;
  dicts: Array<string>;
}
