// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SentenceConstituent = {
  "type": "CompositToken";
  sentence_id: number;
  ids: Array<number>;
  text: string;
  orthography: string;
  start_char: number;
  end_char: number;
} | {
  "type": "SubwordToken";
  sentence_id: number;
  id: number;
  text: string;
  orthography: string;
  lemma: string;
} | {
  "type": "SingleToken";
  sentence_id: number;
  id: number;
  text: string;
  orthography: string;
  lemma: string;
  start_char: number;
  end_char: number;
} | {
  "type": "Whitespace";
  text: string;
  orthography: string;
  start_char: number;
  end_char: number;
};
