// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TokenStatus = "UNMARKED" | "L1" | "L2" | "L3" | "L4" | "L5" | "KNOWN" | "IGNORED";