runembpg:
    cargo run -- --db-choice postgres-embedded --seed

runpg:
    cargo run -- --db-choice postgres-server

runpg-with-seed:
    cargo run -- --db-choice postgres-server --seed

elm-bindings:
    cargo test generate_elm_bindings

fmt:
    cargo fmt

test:
    cargo test