run:
    # uv run python main.py --port 3001 --influx_path ../toy_content
    uv run python main.py --port 3001

test:
    uv run pytest .

test-fix:
    uv run pytest . --inline-snapshot=fix

fmt:
    uv run black .