default:
    just sass & just server

server:
    elm-land server

build:
    elm-land build

sass:
    npm run dev:sass

fmt:
    find src -name "*.elm" ! -name "Bindings.elm" -exec elm-format {} --yes \;